### PR TITLE
Add `cacheFolder` option for caching optimised images

### PR DESCRIPTION
**Pull request by mihaerzen**
I was annoyed by long build times because my project has a lot of large images, so I decided to add caching for already optimised images. I'm more than happy to improve the documentation/code. Feedback greatly appreciated. ✌️

Ref #26

### CODE REVIEW

**Comment by Klathmon** [comment]
I love the addition, however a few other things changed in this PR that made me hesitant to quickly merge it in and I honestly forgot about it for a while!

I'm taking a look at it now, but in the future try to keep PRs for features changing as little outside of the feature addition as possible.

Stuff like the options changes in apply, and the reordering of one of the optimize functions, while nice, make it hard to really identify what was changed for this, and what was just a "nice to have" change.

In the future I'd request that they be done in 2 commits. One to "clean up" things if needed, then another to actually add the functionality. It just makes it easier to review.

I'll take a look now, and I think it's fine, but I just wanted to put that out there. And it goes without saying, thanks a ton for this! It's been a fairly commonly requested feature that I just haven't had time to do myself!

**Comment by mihaerzen** [comment]
@Klathmon Makes sense what you wrote. I actually did it like this but squashed before making a PR ¯\_(ツ)_/¯.

Sorry for the trouble and have a great day!

**Comment by Klathmon** [comment]
No trouble at all! I just feel bad letting a PR languish for like 2 months!

**Comment by RehanSaeed** [comment]
Correct me if I'm wrong but this plugin copies and minifies images in one folder and drops them in another folder and using `cacheFolder` duplicates the minified image in a third cached folder?

Is it possible to simply minify the images in place and keep track of which ones have already been minified?

**Comment by Klathmon** [comment]
Kind of...

So because we are working within webpack for the most part, many files aren't written to disk by this plugin, but are written (or not) by webpack. (For example, if you are using webpack to serve your resources in development, files may never be written to disk at all).

So in order for the caching system to work, it needs to write at least those files to disk, or keep them in memory between runs. 

As far as I know, webpack doesn't give plugins an easy way to keep references to "final" assets around during the next build, so we need to do it ourselves.

That being said, it would be possible to at least do this for the "external images" that are copied and minified as you describe, but it would be a jump in complexity, and it might be difficult to explain how exactly it works and is configured.

If you think you have a good idea on how it can work and can be configured, i'd be open to it, but I don't think I'll be adding that on my own (at least in the near future).

Also, the version in the readme is not yet released (on the road and ran into some problems uploading to NPM, i'm looking to have the beta up tonight.), so the `cacheFolder` option is still not in the latest NPM version.

**Comment by Klathmon** [comment]
Also, I just released [V1.6.0-beta.1](https://github.com/Klathmon/imagemin-webpack-plugin/releases/tag/v1.6.0-beta.1) and would love some feedback on it. (in issue #47)

**Pull request merged**
