### PR TITLE
Add error handling

### PR DESCRIPTION
**Pull request by adriantoine**
Hi! 😃

I've been using this plugin and I had an issue that my webpack build task would fail silently, without showing any errors. I found out it was because this plugin wasn't catching errors, passing them to the callback. This PR fixes it.

Let me know what you think!

Thanks

### CODE REVIEW

**Comment by Klathmon** [comment]
Thanks! I'll merge and bump the version when I get home in a bit.

**Comment by adriantoine** [comment]
Cool thanks!

**Comment by Klathmon** [comment]
I removed the first .catch as it's not necessary. Promise.all will reject on the first rejection in it, so the outer .catch will catch the error and call the callback with it.

**Comment by Klathmon** [comment]
released as 1.0.8

Thanks!

**Pull request merged**
